Notamate1 = float(input("Porfavor ingrese su nota en matemática 1: "))
Notaquim1 = float(input("Porfavor ingrese su nota en quimica 1: "))
Notaintroaprogra = float(input("Porfavor ingrese su nota en introducción a la programación:"))
Notacomunicacion = float(input("Porfavor ingrese su nota en comunicación linguistica: "))
Notaintroainge = float (input("Porfavor ingrese su nota en introducción a la ingenieria en sistemas: "))
Notaestrategias = float(input("Porfavor ingrese su nota en estrategias de razonamiento: "))
Promedio = float((Notamate1 + Notaquim1 + Notaintroaprogra + Notacomunicacion + Notaintroainge + Notaestrategias)/6)
print("Su promedio es de: ",Promedio)
